VARIABLE_1 ?= default_value
VARIABLE_2 := assigned_value
VARIABLE_3 := $(VARIABLE_1) + $(VARIABLE_2)

ifeq ($(VARIABLE_1), value); then
	VARIABLE_4 := value_if_true
else
	VARIABLE_4 := value_if_false
endif

help @:
	@echo "the @ symbol is used to suppress the command from being printed to the console"