name: 'project_name'
version: '1.0'
config-version: 2

profile: 'project name'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  project_name:
        landing:
          materialized: table
          schema: staging
        transform:
          materialized: view
          schema: transform
        analytics:
          materialized: table
          schema: reporting

tests:
  +store_failures: true
  +schema: "tests"

